const PDFDocument = require('pdfkit');

function generateReportPdf(analysis) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const { address, chain, riskScore, riskLevel, issues, profile, recommendation, scannedAt } = analysis;

    doc.fontSize(22).fillColor('#1a1a2e').text('Crypto Risk Analysis Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#666').text('Risk analysis platform — not a definitive scam verdict', { align: 'center' });
    doc.moveDown(1.5);

    doc.fontSize(12).fillColor('#333');
    doc.text(`Address: ${address}`);
    doc.text(`Chain: ${(chain || 'eth').toUpperCase()}`);
    doc.text(`Scanned: ${scannedAt || new Date().toISOString()}`);
    doc.moveDown();

    const riskColor = riskScore > 70 ? '#dc2626' : riskScore > 30 ? '#d97706' : '#16a34a';
    doc.fontSize(18).fillColor(riskColor).text(`Risk Score: ${riskScore}/100 — ${riskLevel}`);
    doc.moveDown();

    doc.fontSize(14).fillColor('#1a1a2e').text('Detected Issues');
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#333');
    for (const issue of issues || []) {
      doc.text(`• [${(issue.severity || 'info').toUpperCase()}] ${issue.message}`);
    }
    doc.moveDown();

    if (profile) {
      doc.fontSize(14).fillColor('#1a1a2e').text('Transaction Summary');
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#333');
      doc.text(`Balance: ${(profile.balanceEth || 0).toFixed(6)} ETH`);
      doc.text(`Total transactions: ${profile.transactionCount || 0}`);
      doc.text(`Incoming: ${profile.incomingCount || 0} | Outgoing: ${profile.outgoingCount || 0}`);
      doc.text(`Token transfers: ${profile.tokenTransferCount || 0}`);
      if (profile.ageDays != null) doc.text(`Wallet age: ~${Math.round(profile.ageDays)} days`);
      doc.moveDown();
    }

    doc.fontSize(14).fillColor('#1a1a2e').text('Final Recommendation');
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#333').text(recommendation || getRecommendation(riskScore));
    doc.moveDown(2);

    doc.fontSize(9).fillColor('#999').text(
      'Disclaimer: This report is generated by automated risk analysis. It cannot detect all scams. ' +
        'Use as one input among many before making financial decisions.',
      { align: 'justify' }
    );

    doc.end();
  });
}

function getRecommendation(score) {
  if (score <= 30) {
    return 'LOW RISK: No major red flags detected. Standard due diligence still recommended before any transaction.';
  }
  if (score <= 70) {
    return 'MEDIUM RISK: Some suspicious indicators found. Proceed with caution and verify the counterparty independently.';
  }
  return 'HIGH RISK: Multiple serious red flags detected. Strongly recommend avoiding transactions with this address until further verification.';
}

module.exports = { generateReportPdf, getRecommendation };
